### ISSUE TITLE
Cannot change default path configuration

### ISSUE THREAD

**Issue by lordgrilo** [antonio-leitao/nau#3]
Apart from the trolling, this is an actual issue. 
We tried to change the default settings but it didn't work too well. 

<img width="653" alt="Screenshot 2023-05-24 at 16 20 20" src="https://github.com/antonio-leitao/nau/assets/2098905/f9d33fd9-bd6b-4e56-b411-6b1a8c6c31ae">

**Comment by antonio-leitao** [comment]
Work in progress haha in a couple of weeks might have a stable release.
The issue I guess it's because the directory does not exist. I guess I can put the feature that it creates one if it does not exist

**Comment by lordgrilo** [comment]
I did create them too but it still doesn't find them.. it's because it looks only in the Documents folder

**Comment by lordgrilo** [comment]
It works if I create them in the Documents folder. 
At that point `nau config` works and lets me configure the rest of the paths etc. 
It seems it gets stuck before the configuration if it doesn't find the directories in the expected path

**Comment by antonio-leitao** [comment]
hmmm, ill look into it over the weekend

**Comment by antonio-leitao** [comment]
This is fixed in version v0.2.0 (commit bf428c64592e006bd79daa19a63396702204c028)
Issue was that running 
```shell
nau config
```
to set up a new config was attempting to load an existing one from the default settings, which obviously didn't exist.
Closing the issue as fixed.
